force-app/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pitch__c/fields/gf_recent_pitch_type__c.field-meta.xml
<CustomField>
    <fullName>gf_recent_pitch_type__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRecentlyCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PitchController.cls
global with sharing class PitchController {

    @AuraEnabled
    global static Boolean getCreated(String recordId){
        Pitch__c isRecentlyCreated = new Pitch__c();
        isRecentlyCreated = [SELECT gf_recent_pitch_type__C from Pitch__c where id=: recordId limit 1];
        return isRecentlyCreated.gf_recent_pitch_type__c;
    }
    /*SINGLETON PATTERN*/
    global static PitchController instance;
    /*global constructor*/
    global PitchController() {
    }
    /*SINGLETON PATTERN*/
    global static PitchController getInstance() { //NOSONAR
        if (instance == null) {
            instance = new PitchController();
        }
        return instance;
    }

}