force-app/main/default/objects/BBVA_Pitch_Team__c/BBVA_Pitch_Team__c.object-meta.xml
<CustomObject>
    <label>BBVA Pitch Team</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BBVA Pitch Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBVA Pitch Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_reference_id__c.field-meta.xml
<CustomField>
    <fullName>external_reference_id__c</fullName>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipLabel>BBVA Pitch Team</relationshipLabel>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_user_id__c.field-meta.xml
<CustomField>
    <fullName>external_user_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pitch__c/fields/country_name__c.field-meta.xml
<CustomField>
    <fullName>country_name__c</fullName>
    <description>Pais en el que tendrá lugar el Pitch</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Compass</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Venezuela</fullName>
            </value>
            <value>
                <fullName>Hong-Kong</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pitch__c/fields/participant_id__c.field-meta.xml
<CustomField>
    <fullName>participant_id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relaciona el registro de Pitch con el cliente</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pitches</relationshipLabel>
    <relationshipName>Pitches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pitch__c/fields/solution_category_name__c.field-meta.xml
<CustomField>
    <fullName>solution_category_name__c</fullName>
    <description>Guarda la familia del producto con el que está relacionado el pitch</description>
    <label>Family Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GTB</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>GF</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pitch__c/fields/solution_name_path_desc__c.field-meta.xml
<CustomField>
    <fullName>solution_name_path_desc__c</fullName>
    <description>Guarda el producto con el que está relacionado el pitch</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>solution_category_name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Client Resources</fullName>
            </value>
            <value>
                <fullName>Corporate Loans</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debt Capital Markets</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>Equity Capital Markets</fullName>
            </value>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Leverage Buyout (LBOs)</fullName>
            </value>
            <value>
                <fullName>Mergers &amp; Acquisitions</fullName>
            </value>
            <value>
                <fullName>Project Finance - Advisory</fullName>
            </value>
            <value>
                <fullName>Project Finance - Lending</fullName>
            </value>
            <value>
                <fullName>Rates</fullName>
            </value>
            <value>
                <fullName>Securities Services</fullName>
            </value>
            <value>
                <fullName>Structured Trade Finance</fullName>
            </value>
            <value>
                <fullName>Transaction Trade Finance</fullName>
            </value>
            <value>
                <fullName>Working Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_opportunity_pitch__c/Related_opportunity_pitch__c.object-meta.xml
<CustomObject>
    <label>Related Opportunity Pitch</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related opportunity pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunity Pitch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_opportunity_pitch__c/fields/opportunity_pitch_id__c.field-meta.xml
<CustomField>
    <fullName>opportunity_pitch_id__c</fullName>
    <description>Relaciona el objeto tipo join (opportunity-pitch) con opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunity Pitch</relationshipLabel>
    <relationshipName>Related_opportunity_pitch</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_opportunity_pitch__c/fields/pitch_opportunity_id__c.field-meta.xml
<CustomField>
    <fullName>pitch_opportunity_id__c</fullName>
    <description>Relaciona el objeto tipo join (opportunity-pitch) con el pitch</description>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipName>Related_opportunity_pitch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PitchUtilTest.cls
/*
* Author         Global Desktop
* Date           2019/10/04
* Description    Clase Util para los tests de Pitch
* Revision
*/
@isTest
public class PitchUtilTest {

  /*Nueva cuenta*/
  public static Account createAccount() {
    Account acc = new Account();
    acc.Name = 'Account Test';
    return acc;
  }

  /*Nuevo pitch*/
  public static Pitch__c createPitch(Account acc) {
    Pitch__c pitchTest = new Pitch__c();
    pitchTest.Name = 'Pitch Test';
    pitchTest.participant_id__c = acc.Id;
    pitchTest.solution_category_name__c = 'GTB';
    pitchTest.solution_name_path_desc__c = 'Cash Management';
    pitchTest.country_name__c = 'Spain';
    return pitchTest;
  }

  /*Nuevo grupo pitch*/
  public static Group createPitchGroup(Pitch__c pitchTest) {
    Group testGroup = new Group();
    testGroup.Name = pitchTest.Id;
    return testGroup;
  }

  /*Nuevo share del pitch*/
  public static Pitch__Share pitchShareTest(Pitch__c pitchTest, BBVA_Pitch_Team__c pitchTeamTest) {
    Pitch__Share pitchShareTest = new Pitch__Share();
    pitchShareTest.ParentId = pitchTest.Id;
    pitchShareTest.UserOrGroupId = pitchTeamTest.external_user_id__c;
    pitchShareTest.AccessLevel = 'Edit';
    return pitchShareTest;
  }

  /*Nuevo usuario*/
  public static User createUser() {
    Id profId = [Select Id from Profile Limit 1].Id;
    User userTest = new User();
    userTest.Lastname ='LastNameTest';
    userTest.Alias = 'Alias';
    userTest.Email = 'Alias@bbva.com';
    userTest.username = createUserName() + '@bbva.com';
    userTest.CommunityNickname = createUserName() + 'ComunityNickNameTest2';
    userTest.ProfileId = profId;
    userTest.EmailEncodingKey = 'UTF-8';
    userTest.Timezonesidkey='Europe/London';
    userTest.Localesidkey='en_US';
    userTest.languagelocalekey='en_US';
    return userTest;
  }

  /*Nuevo userName*/
  public static string createUserName() {
    return 'test_' + string.valueOf(system.now().hour()) + string.valueOf(system.now().minute()) + string.valueOf(system.now().second()) + string.valueOf(system.now().millisecond());
  }

  /*Nuevo equipo del pitch*/
  public static BBVA_Pitch_Team__c createPitchTeam(Pitch__c pitch, User userTest) {
    BBVA_Pitch_Team__c pitchTeam = new BBVA_Pitch_Team__c();
    pitchTeam.external_reference_id__c = pitch.Id;
    pitchTeam.external_user_id__c = userTest.Id;
    return pitchTeam;
  }

  /*Nueva oportunidad*/
  public static Opportunity createOpportunity(Account acc) {
    Opportunity oppTest = new Opportunity();
    oppTest.Name = 'Opportunity Test';
    oppTest.AccountId = acc.Id;
    oppTest.CloseDate = system.today();
    oppTest.StageName = 'Prospecting';
    return oppTest;
  }

  /*Nueva relacion entre oportunidad y pitch*/
  public static Related_opportunity_pitch__c createRelOppPitch(Opportunity opp, Pitch__c pitchTest) {
    Related_opportunity_pitch__c relPitchOpp = new Related_opportunity_pitch__c();
    relPitchOpp.opportunity_pitch_id__c = opp.Id;
    relPitchOpp.pitch_opportunity_id__c = pitchTest.Id;
    return relPitchOpp;
  }

  /*Nuevo miembro de la oportunidad*/
  public static OpportunityTeamMember createOppTeam(Opportunity opp, User userTest) {
    OpportunityTeamMember oppTeam = new OpportunityTeamMember();
    oppTeam.OpportunityId = opp.Id;
    oppTeam.UserId = userTest.Id;
    return oppTeam;
  }

  /*Nueva visita*/
  public static dwp_kitv__Visit__c createVisit(Account acc, Opportunity opp) {
    dwp_kitv__Visit__c vis = new dwp_kitv__Visit__c();
    vis.dwp_kitv__account_id__c= acc.Id;
    vis.Name = 'VISIT TEST';
    vis.dwp_kitv__visit_duration_number__c = '15';
    vis.dwp_kitv__visit_start_date__c = Date.today();
    return vis;
  }

  /*Nuevo VisitTopic*/
  public static dwp_kitv__Visit_Topic__c createVisitTopic(dwp_kitv__Visit__c vis, Opportunity opp) {
    dwp_kitv__Visit_Topic__c visTopic = new dwp_kitv__Visit_Topic__c();
    visTopic.dwp_kitv__visit_id__c = vis.Id;
    visTopic.dwp_kitv__opportunity_id__c = opp.id;
    visTopic.dwp_kitv__topic_desc__c = 'VISIT TOPIC TEST';
    return visTopic;
  }

  /*Nuevo miembro del equipo de la visita*/
  public static dwp_kitv__Visit_Management_Team__c createVisitTeam(dwp_kitv__Visit__c vis, User user) {
    dwp_kitv__Visit_Management_Team__c visTeam = new dwp_kitv__Visit_Management_Team__c();
    visTeam.dwp_kitv__visit_id__c = vis.Id;
    visTeam.dwp_kitv__user_id__c = user.Id;
    return visTeam;
  }

}