force-app/main/default/objects/BBVA_Pitch_Team__c/BBVA_Pitch_Team__c.object-meta.xml
<CustomObject>
    <label>BBVA Pitch Team</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BBVA Pitch Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBVA Pitch Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_reference_id__c.field-meta.xml
<CustomField>
    <fullName>external_reference_id__c</fullName>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipLabel>BBVA Pitch Team</relationshipLabel>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_user_id__c.field-meta.xml
<CustomField>
    <fullName>external_user_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/dwp_kitv__Visit_Topic__c/fields/pitch_visit_topic_id__c.field-meta.xml
<CustomField>
    <fullName>pitch_visit_topic_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relaciona el objeto Visit Topic con el Pitch</description>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipLabel>Visit Topics</relationshipLabel>
    <relationshipName>Visit_Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitRelPitchTriggerHandler.cls
/************************************************************************
Name:            VisitRelPitchTriggerHandler
Description:     Handler del trigger de Visit Topic
Test Class:

Version        Date            Author            Summary of changes
---------------------------------------------------------------------------------------------
1              22/08/2018      Global Desktop    Class creation
*************************************************************************/
global without sharing class VisitRelPitchTriggerHandler {

  /*
  * @author Global Desktop
  * @Description Inserta los miembros del equipo de la oportunidad relacionada en el equipo del pitch
  */
  global void completePitchTeam(List<dwp_kitv__Visit_Topic__c > visitTopicList) {
    if(visitTopicList.size() <= 1) {
      final List<dwp_kitv__Visit_Management_Team__c> visitTeamList = [SELECT dwp_kitv__user_id__c,
                                                                      dwp_kitv__user_id__r.Name
                                                                      FROM dwp_kitv__Visit_Management_Team__c
                                                                      WHERE dwp_kitv__visit_id__c = :visitTopicList[0].dwp_kitv__visit_id__c];

      List<BBVA_Pitch_Team__c> allPitchTeamList = [SELECT Id, external_user_id__c, external_reference_id__c
                                                  FROM BBVA_Pitch_Team__c
                                                  WHERE external_reference_id__c =: visitTopicList[0].pitch_visit_topic_id__c];
      map<String, String> pitchUser = new map<String, String>();
      for(BBVA_Pitch_Team__c allPitchTeam : allPitchTeamList) {
        pitchUser.put(allPitchTeam.external_user_id__c, allPitchTeam.external_user_id__c);
      }

      final List<BBVA_Pitch_Team__c> pitchTeamList = new List<BBVA_Pitch_Team__c>();
      for(dwp_kitv__Visit_Management_Team__c visitTeam : visitTeamList) {
        if(pitchUser.get(visitTeam.dwp_kitv__user_id__c) == null) {
          BBVA_Pitch_Team__c pitchTeam = new BBVA_Pitch_Team__c();
          pitchTeam.external_reference_id__c = visitTopicList[0].pitch_visit_topic_id__c;
          pitchTeam.external_user_id__c = visitTeam.dwp_kitv__user_id__c;
          pitchTeamList.add(pitchTeam);
        }
      }
      insert pitchTeamList;
    }
  }
}