force-app/main/default/objects/BBVA_Pitch_Team__c/BBVA_Pitch_Team__c.object-meta.xml
<CustomObject>
    <label>BBVA Pitch Team</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BBVA Pitch Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBVA Pitch Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_reference_id__c.field-meta.xml
<CustomField>
    <fullName>external_reference_id__c</fullName>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipLabel>BBVA Pitch Team</relationshipLabel>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_user_id__c.field-meta.xml
<CustomField>
    <fullName>external_user_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BBVAPitchTeamHandler.cls
/********************************************************************************************
Name:            BBVAPitchTeamHandler
Description:     Handler del trigger BBVAPitchTeam
Test Class:

Version        Date            Author            Summary of changes
---------------------------------------------------------------------------------------------
1              12/08/2018      Global Desktop    Class creation
*********************************************************************************************/
global without sharing class BBVAPitchTeamHandler {

  /*
    * @author Global Desktop
    * @Description Busca los nuevos usuarios incluidos al equipo del pitch
    */
    global void completePublicGroup(List<BBVA_Pitch_Team__c> pitchTeamList) {
      final List<Group> groupRecord = [SELECT Id FROM Group WHERE Name = :pitchTeamList[0].external_reference_id__c LIMIT 1];
      final set<Id> usersId = new set<Id>();
      for(BBVA_Pitch_Team__c pitchTeam : pitchTeamList) {
        usersId.add(pitchTeam.external_user_id__c);
      }
      insertMemberGroup(usersId,groupRecord[0].Id);
    }

    /*
    * @author Global Desktop
    * @Description Inserta los groupMember
    */
    @future
    public static void insertMemberGroup(set<Id> usersId,Id groupRecord) {
      final List<GroupMember> groupMemberList = new List<GroupMember>();
      for(Id userId : usersId) {
        GroupMember groupMember = new GroupMember();
      groupMember.GroupId = groupRecord;
      groupMember.UserOrGroupId  = userId;
      groupMemberList.add(groupMember);
      }
      insert groupMemberList;
    }

    /*
    * @author Global Desktop
    * @Description Recupera el usuario y el grupo relacionado con el registro que se quiere borrar.
    */
    global void getGroupMember(List<BBVA_Pitch_Team__c> pitchTeamList) {
      final Id userId = pitchTeamList[0].external_user_id__c;
      final Id groupId = [SELECT Id FROM Group WHERE Name = :pitchTeamList[0].external_reference_id__c LIMIT 1].Id;
    deleteGroupMember(userId, groupId);
    }

    /*
    * @author Global Desktop
    * @Description Borra del grupo al usuario borrado del equipo del pitch
    */
    @future
    public static void deleteGroupMember(Id userId, Id groupId) {
      final List<GroupMember> groupMemberList = [SELECT Id
                        FROM GroupMember
                        WHERE GroupId = :groupId
                        AND UserOrGroupId = :userId LIMIT 1];
      delete groupMemberList[0];
    }

}