force-app/main/default/objects/BBVA_Pitch_Team__c/BBVA_Pitch_Team__c.object-meta.xml
<CustomObject>
    <label>BBVA Pitch Team</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BBVA Pitch Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBVA Pitch Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_reference_id__c.field-meta.xml
<CustomField>
    <fullName>external_reference_id__c</fullName>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipLabel>BBVA Pitch Team</relationshipLabel>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/external_user_id__c.field-meta.xml
<CustomField>
    <fullName>external_user_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BBVA_Pitch_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BBVA_Pitch_Team__c/fields/role_desc__c.field-meta.xml
<CustomField>
    <fullName>role_desc__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager FI</fullName>
            </value>
            <value>
                <fullName>Account Manager FX</fullName>
            </value>
            <value>
                <fullName>Account Manager EQ</fullName>
            </value>
            <value>
                <fullName>Sales FI</fullName>
            </value>
            <value>
                <fullName>Sales FX</fullName>
            </value>
            <value>
                <fullName>Sales EQ</fullName>
            </value>
            <value>
                <fullName>Analyst FI</fullName>
            </value>
            <value>
                <fullName>Analyst FX</fullName>
            </value>
            <value>
                <fullName>Analyst EQ</fullName>
            </value>
            <value>
                <fullName>Sales HY</fullName>
            </value>
            <value>
                <fullName>Sales Govies</fullName>
            </value>
            <value>
                <fullName>Sales Credit</fullName>
            </value>
            <value>
                <fullName>Sales Emergents</fullName>
            </value>
            <value>
                <fullName>Global Banker Team</fullName>
            </value>
            <value>
                <fullName>CIB Banker</fullName>
            </value>
            <value>
                <fullName>Industry Head</fullName>
            </value>
            <value>
                <fullName>Local Banker</fullName>
            </value>
            <value>
                <fullName>Regional Banker</fullName>
            </value>
            <value>
                <fullName>Product Specialist</fullName>
            </value>
            <value>
                <fullName>Risk Analyst</fullName>
            </value>
            <value>
                <fullName>Global Banker</fullName>
            </value>
            <value>
                <fullName>GCC pool</fullName>
            </value>
            <value>
                <fullName>Transactional Banker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pitch__c/Pitch__c.object-meta.xml
<CustomObject>
    <label>Pitch</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pitches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_opportunity_pitch__c/Related_opportunity_pitch__c.object-meta.xml
<CustomObject>
    <label>Related Opportunity Pitch</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related opportunity pitch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunity Pitch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_opportunity_pitch__c/fields/opportunity_pitch_id__c.field-meta.xml
<CustomField>
    <fullName>opportunity_pitch_id__c</fullName>
    <description>Relaciona el objeto tipo join (opportunity-pitch) con opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunity Pitch</relationshipLabel>
    <relationshipName>Related_opportunity_pitch</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_opportunity_pitch__c/fields/pitch_opportunity_id__c.field-meta.xml
<CustomField>
    <fullName>pitch_opportunity_id__c</fullName>
    <description>Relaciona el objeto tipo join (opportunity-pitch) con el pitch</description>
    <label>Pitch</label>
    <referenceTo>Pitch__c</referenceTo>
    <relationshipName>Related_opportunity_pitch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OppRelPitchTriggerHandler.cls
/********************************************************************************************
Name:            OppRelPitchTriggerHandler
Description:     Handler del trigger OppRelPitchTrigger
Test Class:

Version        Date            Author            Summary of changes
---------------------------------------------------------------------------------------------
1              16/08/2018      Global Desktop    Class creation
*********************************************************************************************/
global without sharing class OppRelPitchTriggerHandler {

    /*
    * @author Global Desktop
    * @Description Inserta los miembros del equipo de la oportunidad relacionada en el equipo del pitch
    */
    global void completePitchTeam(List<Related_opportunity_pitch__c > oppPitchList) {
        if(oppPitchList.size() <= 1) {
            final List<OpportunityTeamMember> oppTeamList = [SELECT UserId, User.Name, TeamMemberRole
                                                        FROM OpportunityTeamMember
                                                        WHERE OpportunityId = :oppPitchList[0].opportunity_pitch_id__c];

            //////////////////////////////
            //Pitch__c pitch = [SELECT Id FROM Pitch__c WHERE Id =: oppPitchList[0].pitch_opportunity_id__c LIMIT 1];
            List<BBVA_Pitch_Team__c> allPitchTeamList = [SELECT Id, external_user_id__c, external_reference_id__c
                                                    FROM BBVA_Pitch_Team__c
                                                    WHERE external_reference_id__c =: oppPitchList[0].pitch_opportunity_id__c];
            map<String, String> pitchUser = new map<String, String>();
            for(BBVA_Pitch_Team__c allPitchTeam : allPitchTeamList) {
                pitchUser.put(allPitchTeam.external_user_id__c, allPitchTeam.external_user_id__c);
            }

            //////////////////////////////

            final List<BBVA_Pitch_Team__c> pitchTeamList = new List<BBVA_Pitch_Team__c>();
            for(OpportunityTeamMember oppTeam : oppTeamList) {
                if(pitchUser.get(oppTeam.UserId) == null) {
                    BBVA_Pitch_Team__c pitchTeam = new BBVA_Pitch_Team__c();
                    pitchTeam.external_reference_id__c = oppPitchList[0].pitch_opportunity_id__c;
                    pitchTeam.external_user_id__c = oppTeam.UserId;
                    //pitchTeam.Name = oppTeam.User.Name;
                    pitchTeam.role_desc__c = oppTeam.TeamMemberRole;
                    pitchTeamList.add(pitchTeam);
                }
            }
            insert pitchTeamList;
        }
    }

}